### ISSUE TITLE
Still some commits incoming?

### ISSUE THREAD

**Issue by Safraann** [SystematicSkid/SWBF2#1]
Hi SystematicSkid,
I know that this repo is 15 months old, but I was hoping that there were still some researches done that hadn't been uploaded since now? I'm very interested in reversing this game, do you have more reversed data by any chance? Thanks in advance!

**Comment by SystematicSkid** [comment]
Hi, I might look into the game in the future again, I think I did some work on it just a few months ago, but likely not much noticeable.

**Comment by Safraann** [comment]
Ok, if you wanna cooperate with me I'll be happy. I'm trying to get my w2s working right now, I've already found all the necessary matrices, just need some math to debug the whole thing =)

**Comment by SystematicSkid** [comment]
I don't have much free time nowadays to work on projects like that, but if I have a chance I'll probably remake the entire project.

**Comment by SystematicSkid** [comment]
I decided to rewrite the entire base, took me about two hours to build a basic class-name ESP, you can view it here:
https://github.com/SystematicSkid/SWBF2-2020
